# Generated by Django 4.1.5 on 2023-01-16 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], default=1, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(blank=True, upload_to='images')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
